-- Durable work queue for the one-off IMPECT historical event backfill.
-- Discovery is cheap and repeatable; processing claims a bounded batch, so a
-- runner timeout or provider error never loses progress or redoes successes.

USE DATABASE CAFC_DB;

CREATE TABLE IF NOT EXISTS CAFC_DB.CORE.IMPECT_EVENT_BACKFILL_QUEUE (
  MATCH_ID             NUMBER(38,0) NOT NULL,
  ITERATION_ID         NUMBER(38,0) NOT NULL,
  COMPETITION_NAME     VARCHAR,
  SEASON               VARCHAR,
  SCHEDULED_AT         TIMESTAMP_NTZ,
  STATUS               VARCHAR NOT NULL DEFAULT 'PENDING',
  ATTEMPT_COUNT        NUMBER(38,0) NOT NULL DEFAULT 0,
  NEXT_ATTEMPT_AT      TIMESTAMP_NTZ,
  CLAIMED_BY           VARCHAR,
  CLAIMED_AT           TIMESTAMP_NTZ,
  EVENT_COUNT          NUMBER(38,0),
  LAST_ERROR           VARCHAR,
  INGESTION_RUN_ID     NUMBER(38,0),
  CREATED_AT           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT         TIMESTAMP_NTZ,
  CONSTRAINT IMPECT_EVENT_BACKFILL_QUEUE_PK PRIMARY KEY (MATCH_ID)
)
COMMENT = 'Resumable historical IMPECT event backfill queue. Terminal statuses are SUCCESS and NO_EVENT_DATA.';

CREATE TABLE IF NOT EXISTS CAFC_DB.CORE.IMPECT_EVENT_BACKFILL_DISCOVERY (
  ITERATION_ID         NUMBER(38,0) NOT NULL,
  COMPETITION_NAME     VARCHAR,
  SEASON               VARCHAR,
  STATUS               VARCHAR NOT NULL DEFAULT 'PENDING',
  CLAIMED_BY           VARCHAR,
  CLAIMED_AT           TIMESTAMP_NTZ,
  LAST_ERROR           VARCHAR,
  DISCOVERED_MATCHES   NUMBER(38,0),
  CREATED_AT           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT         TIMESTAMP_NTZ,
  CONSTRAINT IMPECT_EVENT_BACKFILL_DISCOVERY_PK PRIMARY KEY (ITERATION_ID)
)
COMMENT = 'Resumable catalogue-discovery queue for the IMPECT historical event backfill.';
