-- ============================================================================
--  20260611_phase4_move_remaining_app_tables_to_core.sql
--  Phase 4 platform half: move the remaining app-owned tables from
--  RECRUITMENT_TEST.PUBLIC (legacy) to CAFC_DB.CORE — the tables whose app
--  writes were templated in app Phase 4 but never got a CORE home. Found by
--  the 2026-06-11 cutover audit: full-cutover writes to these would have
--  failed (table missing), and CORE.USERS was a stale months-old copy
--  (51 rows vs 174 live — logins would have broken at flip).
--
--  Same mechanics as 20260610_phase3_move_scout_lists_to_core.sql:
--  CREATE OR REPLACE ... CLONE is zero-copy, re-runnable, and MUST be re-run
--  inside the cutover write freeze. Run with a role that owns CAFC_DB.CORE.
--
--  NOT moved (legacy tables with no app references in backend/main.py —
--  confirm dead, then archive with the legacy DB): NOTIFICATIONS,
--  SCOUT_ASSIGNMENTS, SCOUT_ASSIGNMENT_PLAYERS, SCOUT_ASSIGNMENT_AUDIT.
-- ============================================================================

-- ---- 1. Snapshot legacy first (skip if phase-3 script just ran) ------------
CREATE DATABASE IF NOT EXISTS RECRUITMENT_TEST_PRE_PHASE4 CLONE RECRUITMENT_TEST;

-- ---- 2. Move the seven remaining app-owned tables ---------------------------
CREATE OR REPLACE TABLE CAFC_DB.CORE.USERS                  CLONE RECRUITMENT_TEST.PUBLIC.USERS;
CREATE OR REPLACE TABLE CAFC_DB.CORE.PLAYER_NOTES           CLONE RECRUITMENT_TEST.PUBLIC.PLAYER_NOTES;
CREATE OR REPLACE TABLE CAFC_DB.CORE.PLAYER_INFORMATION     CLONE RECRUITMENT_TEST.PUBLIC.PLAYER_INFORMATION;
CREATE OR REPLACE TABLE CAFC_DB.CORE.AGENT_PROFILES         CLONE RECRUITMENT_TEST.PUBLIC.AGENT_PROFILES;
CREATE OR REPLACE TABLE CAFC_DB.CORE.PLAYER_RECOMMENDATIONS CLONE RECRUITMENT_TEST.PUBLIC.PLAYER_RECOMMENDATIONS;
CREATE OR REPLACE TABLE CAFC_DB.CORE.PLAYER_STAGE_HISTORY   CLONE RECRUITMENT_TEST.PUBLIC.PLAYER_STAGE_HISTORY;
CREATE OR REPLACE TABLE CAFC_DB.CORE.STATUS_HISTORY         CLONE RECRUITMENT_TEST.PUBLIC.STATUS_HISTORY;

-- ---- 3. Grants (clones do not inherit grants) ------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.USERS                  TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.PLAYER_NOTES           TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.PLAYER_INFORMATION     TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.AGENT_PROFILES         TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.PLAYER_RECOMMENDATIONS TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.PLAYER_STAGE_HISTORY   TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAFC_DB.CORE.STATUS_HISTORY         TO ROLE APP_ROLE;

GRANT SELECT ON CAFC_DB.CORE.USERS                  TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.PLAYER_NOTES           TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.PLAYER_INFORMATION     TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.AGENT_PROFILES         TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.PLAYER_RECOMMENDATIONS TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.PLAYER_STAGE_HISTORY   TO ROLE DATA_PLATFORM_ROLE;
GRANT SELECT ON CAFC_DB.CORE.STATUS_HISTORY         TO ROLE DATA_PLATFORM_ROLE;

-- ---- 4. Parity check (inside the freeze; any mismatch → re-run section 2) --
SELECT 'USERS' t,
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.USERS) legacy_n,
       (SELECT COUNT(*) FROM CAFC_DB.CORE.USERS) core_n
UNION ALL SELECT 'PLAYER_NOTES',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.PLAYER_NOTES),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.PLAYER_NOTES)
UNION ALL SELECT 'PLAYER_INFORMATION',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.PLAYER_INFORMATION),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.PLAYER_INFORMATION)
UNION ALL SELECT 'AGENT_PROFILES',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.AGENT_PROFILES),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.AGENT_PROFILES)
UNION ALL SELECT 'PLAYER_RECOMMENDATIONS',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.PLAYER_RECOMMENDATIONS),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.PLAYER_RECOMMENDATIONS)
UNION ALL SELECT 'PLAYER_STAGE_HISTORY',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.PLAYER_STAGE_HISTORY),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.PLAYER_STAGE_HISTORY)
UNION ALL SELECT 'STATUS_HISTORY',
       (SELECT COUNT(*) FROM RECRUITMENT_TEST.PUBLIC.STATUS_HISTORY),
       (SELECT COUNT(*) FROM CAFC_DB.CORE.STATUS_HISTORY);
