-- Run after MATCH_INFO backfill and the participation dbt build.

-- Must return zero.
SELECT COUNT(DISTINCT e.MATCH_ID) AS EVENT_MATCHES_WITHOUT_MATCH_INFO
FROM CAFC_DB.IMPECT_RAW.EVENTS e
LEFT JOIN CAFC_DB.IMPECT_RAW.MATCH_INFO m ON m.MATCH_ID = e.MATCH_ID
WHERE m.MATCH_ID IS NULL;

-- Duration parity against the legacy Championship fixture KPI source.
WITH calculated AS (
  SELECT
    IMPECT_MATCH_ID AS MATCH_ID,
    IMPECT_PLAYER_ID AS PLAYER_ID,
    IMPECT_SQUAD_ID AS SQUAD_ID,
    POSITION_CODE,
    SUM(PLAY_DURATION_SECONDS) AS PLAY_DURATION_SECONDS
  FROM CAFC_DB.IMPECT_RAW_STAGING.STG_IMPECT__PLAYER_FIXTURE_POSITION_PARTICIPATION
  GROUP BY 1,2,3,4
),
authoritative AS (
  SELECT DISTINCT
    MATCHID AS MATCH_ID,
    PLAYERID AS PLAYER_ID,
    SQUADID AS SQUAD_ID,
    POSITION AS POSITION_CODE,
    PLAYDURATION AS PLAY_DURATION_SECONDS
  FROM CAFC_DB.IMPECT_RAW.CHAMPIONSHIP_PLAYER_KPIS
  WHERE PLAYDURATION > 0
),
compared AS (
  SELECT
    COALESCE(c.MATCH_ID, a.MATCH_ID) AS MATCH_ID,
    COALESCE(c.PLAYER_ID, a.PLAYER_ID) AS PLAYER_ID,
    COALESCE(c.SQUAD_ID, a.SQUAD_ID) AS SQUAD_ID,
    COALESCE(c.POSITION_CODE, a.POSITION_CODE) AS POSITION_CODE,
    c.PLAY_DURATION_SECONDS AS CALCULATED_SECONDS,
    a.PLAY_DURATION_SECONDS AS AUTHORITATIVE_SECONDS,
    ABS(c.PLAY_DURATION_SECONDS - a.PLAY_DURATION_SECONDS) AS DELTA_SECONDS
  FROM calculated c
  FULL OUTER JOIN authoritative a
    ON a.MATCH_ID = c.MATCH_ID
   AND a.PLAYER_ID = c.PLAYER_ID
   AND a.SQUAD_ID = c.SQUAD_ID
   AND a.POSITION_CODE = c.POSITION_CODE
)
SELECT
  COUNT(*) AS PLAYER_POSITION_ROWS,
  COUNT_IF(CALCULATED_SECONDS IS NULL) AS MISSING_CALCULATED,
  COUNT_IF(AUTHORITATIVE_SECONDS IS NULL) AS MISSING_AUTHORITATIVE,
  MEDIAN(DELTA_SECONDS) AS MEDIAN_DELTA_SECONDS,
  PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY DELTA_SECONDS) AS P95_DELTA_SECONDS,
  MAX(DELTA_SECONDS) AS MAX_DELTA_SECONDS
FROM compared;

