#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# This wizard's captured values (server IP, worker count, tuning knobs) are
# bookkeeping for re-runs, not application config, so keep them out of the
# extractor's real .env.
ENV_FILE="$HOME/.cafc-backfill-wizard.env"

# Locate the extractor directory whether this is run from the repo root or
# from python/extract/impect itself.
IMPECT_DIR=""
for _cand in "python/extract/impect" "." "$(cd "$(dirname "$0")" && pwd)"; do
  if [[ -f "$_cand/backfill_historical_match_events.py" ]]; then IMPECT_DIR="$_cand"; break; fi
done
if [[ -z "$IMPECT_DIR" ]]; then
  echo "Could not find python/extract/impect. Run this from the repo root." >&2
  exit 1
fi
IMPECT_DIR="$(cd "$IMPECT_DIR" && pwd)"

SSH_KEY_PATH="$HOME/.ssh/id_ed25519"
_ssh() { ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -i "$SSH_KEY_PATH" "root@$SERVER_IP" "$@"; }

banner "DigitalOcean backfill setup"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Local prerequisites"
say "Checking this machine has what the wizard needs."
_missing=""
for _bin in ssh rsync ssh-keygen; do
  command -v "$_bin" >/dev/null 2>&1 || _missing="$_missing $_bin"
done
[[ -n "$_missing" ]] && { warn "missing:$_missing"; exit 1; }
[[ -f "$IMPECT_DIR/.env" ]] || {
  warn "No $IMPECT_DIR/.env — copy .env.example to .env and fill it in first."; exit 1; }
[[ -f "$IMPECT_DIR/keys/rsa_key_unencrypted.pem" ]] || {
  warn "No Snowflake key at $IMPECT_DIR/keys/rsa_key_unencrypted.pem"; exit 1; }
[[ -f "$IMPECT_DIR/run_queue_backfill_lanes.sh" ]] || {
  warn "Missing $IMPECT_DIR/run_queue_backfill_lanes.sh (the parallel queue launcher)."; exit 1; }
say "OK — using extractor at: $IMPECT_DIR"
note "Local .env and Snowflake key found; both get copied to the server later."
pause "Continue?"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "SSH key for the server"
if [[ -f "$SSH_KEY_PATH" ]]; then
  say "Using existing key: $SSH_KEY_PATH"
else
  warn "No SSH key at $SSH_KEY_PATH."
  if confirm "Create an ed25519 key now?"; then
    ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -C "impect-backfill"
  else
    say "Point SSH_KEY_PATH in this script at an existing private key, then re-run."
    exit 1
  fi
fi
echo
say "Public key — you'll paste this into DigitalOcean in the next stage:"
echo
cat "$SSH_KEY_PATH.pub"
echo
pause "Copied it to your clipboard?"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "DigitalOcean account"
open_url "https://cloud.digitalocean.com/registrations/new"
step "Sign up, or log in if you already have an account."
step "Add a payment method — new accounts get a small temporary card authorisation."
warn "New accounts occasionally get a brief verification hold. If so, wait for the confirmation email — you can Ctrl-C and re-run this wizard later."
pause "Logged in and looking at the DigitalOcean control panel?"

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Create the Droplet"
open_url "https://cloud.digitalocean.com/droplets/new"
step "Region: Frankfurt (FRA1) or Amsterdam (AMS3) — closest to Impect's API."
step "Choose an image: Ubuntu 24.04 (LTS) x64."
step "Droplet type: Basic. CPU options: Regular (Disk type: SSD)."
step "Size: \$12/mo (1 vCPU / 2 GB RAM / 50 GB SSD / 2 TB transfer). Enough headroom for 5 workers."
note "Squeezing costs? The \$6/mo (1 GB) size works with 3 workers. A faster/bigger box buys nothing — the backfill is rate-limited by Impect, not CPU."
step "Authentication: SSH Key → 'New SSH Key' → paste the public key from the previous stage → give it a name."
step "Hostname: impect-backfill. Leave the rest default. Create Droplet."
say "Wait until the Droplet is 'Active' and shows a public IPv4 address."
pause "Droplet active?"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Connect to the server"
ask SERVER_IP "Paste the server's public IPv4:"
[[ -n "${SERVER_IP:-}" ]] || { warn "No IP entered."; exit 1; }
write_env SERVER_IP "$SERVER_IP"
say "Testing SSH to root@$SERVER_IP ..."
until ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -i "$SSH_KEY_PATH" "root@$SERVER_IP" true 2>/dev/null; do
  warn "Couldn't connect yet (the server may still be booting)."
  confirm "Retry?" || { say "Check the IP and that your SSH key was attached in the console, then re-run."; exit 1; }
done
say "SSH OK."

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Snowflake network policy"
open_url "https://app.snowflake.com/"
say "In a Snowsight worksheet, run:"
note "  SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN ACCOUNT;"
note "  SHOW NETWORK POLICIES;"
step "If no network policy is set (blank value, nothing listed): nothing to do."
step "If one IS set, allow this server through it:"
note "  ALTER NETWORK POLICY <policy_name>"
note "    SET ALLOWED_IP_LIST = (<keep existing IPs...>, '$SERVER_IP');"
warn "Skip this when a policy exists and the smoke test's Snowflake connection will fail with an IP error."
pause "Done — updated the policy, or confirmed there isn't one?"

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Provision & deploy"
say "Installing packages on the server..."
_ssh 'apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-venv python3-pip rsync tmux setsid || DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-venv python3-pip rsync tmux'
say "Copying code + credentials to /root/impect ..."
rsync -az --delete \
  --exclude '.venv' --exclude 'backfill_logs' --exclude '__pycache__' \
  --exclude '.impect_token_cache.json' \
  -e "ssh -o StrictHostKeyChecking=accept-new -i $SSH_KEY_PATH" \
  "$IMPECT_DIR/" "root@$SERVER_IP:/root/impect/"
_ssh 'chmod 700 /root/impect/keys && chmod 600 /root/impect/keys/* /root/impect/.env && chmod +x /root/impect/*.sh'
say "Building the Python environment (1-3 min)..."
_ssh 'cd /root/impect && python3 -m venv .venv && .venv/bin/pip install -q --upgrade pip && .venv/bin/pip install -q -r requirements.txt'
say "Deployed."

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "Tuning (optional)"
say "Press Enter to skip either of these."
ask WAREHOUSE_OVERRIDE "Override SNOWFLAKE_WAREHOUSE in the server's .env? (recommend an XS warehouse with AUTO_SUSPEND 60; blank = keep current):"
if [[ -n "${WAREHOUSE_OVERRIDE:-}" ]]; then
  _ssh "cd /root/impect && sed -i '/^SNOWFLAKE_WAREHOUSE=/d' .env && echo 'SNOWFLAKE_WAREHOUSE=$WAREHOUSE_OVERRIDE' >> .env"
  write_env WAREHOUSE_OVERRIDE "$WAREHOUSE_OVERRIDE"
  say "Set SNOWFLAKE_WAREHOUSE=$WAREHOUSE_OVERRIDE on the server."
fi
ask PACE_FLOOR "Fixed minimum seconds between Impect requests per worker? (blank = adaptive pacing only; try 0.5 if 429s stay heavy):"
if [[ -n "${PACE_FLOOR:-}" ]]; then
  _ssh "cd /root/impect && sed -i '/^IMPECT_MIN_REQUEST_INTERVAL=/d' .env && echo 'IMPECT_MIN_REQUEST_INTERVAL=$PACE_FLOOR' >> .env"
  write_env PACE_FLOOR "$PACE_FLOOR"
  say "Set IMPECT_MIN_REQUEST_INTERVAL=$PACE_FLOOR on the server."
fi

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage "Smoke test"
say "Checking Impect + Snowflake auth from the server (prints backfill queue counts)..."
echo
_ssh 'cd /root/impect && .venv/bin/python3 backfill_historical_match_events.py --status' || true
echo
confirm "Did that print queue counts (PENDING in the tens of thousands)?" || {
  warn "Stop here. Usual causes: wrong values in the server's .env, or the Snowflake network policy still blocking $SERVER_IP."
  say  "Fix it, then re-run this wizard — it resumes from saved values."
  exit 1
}

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage "Launch the backfill"
ask LANES "How many parallel workers? (default 5):"
[[ -n "${LANES:-}" ]] || LANES=5
write_env LANES "$LANES"
say "Starting $LANES worker(s), detached so they survive logout..."
_ssh "cd /root/impect && mkdir -p backfill_logs && setsid nohup ./run_queue_backfill_lanes.sh $LANES > backfill_logs/queue_launcher.log 2>&1 < /dev/null & echo started"
sleep 8
say "Worker processes now running:"
_ssh 'pgrep -af "backfill_historical_match_events.py --process" | head -n 8 || echo "(none yet)"'
echo
say "First worker log:"
_ssh 'tail -n 12 /root/impect/backfill_logs/queue_worker_1.log 2>/dev/null || echo "(no worker log yet — check backfill_logs/queue_launcher.log)"'
pause "Looks like it's fetching matches?"

# ── Stage 11 ─────────────────────────────────────────────────────────────
stage "Monitoring & teardown"
_c="ssh -i $SSH_KEY_PATH root@$SERVER_IP"
say "Progress:   $_c 'cd /root/impect && .venv/bin/python3 backfill_historical_match_events.py --status'"
say "Live log:   $_c 'tail -f /root/impect/backfill_logs/queue_worker_1.log'"
say "Processes:  $_c 'pgrep -af backfill_historical_match_events.py'"
say "Stop all:   $_c 'pkill -f backfill_historical_match_events.py; pkill -f run_queue_backfill_lanes'"
echo
warn "When 'status' shows 0 PENDING:"
say "  1. Destroy the Droplet in the DigitalOcean control panel — this is what stops billing (a powered-off Droplet still costs)."
say "  2. Remove $SERVER_IP from the Snowflake network policy if you added it in stage 6."
say "  3. Raise the warehouse AUTO_SUSPEND back if you lowered it for the run."
note "Rough expectation: ~100 matches/hr sustained → multiple weeks for ~120k matches."
pause "Done"

finish
